name: RSpec 

on: pull_request

jobs:
  RSpec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Setup database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run RSpec
        run: bundle exec rspec
  
  # Rubocop:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup Ruby Env
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.1.2'
  #         bundler-cache: true
  #         # 依存関係のインストールをスピードアップする

  #     - name: Run Rubocop
  #       run: bundle exec rubocop
