name: RSpec Actions
on: pull_request

jobs:
  RSpec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
        # サービスコンテナ

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
          # 依存関係のインストールをスピードアップする

      - name: Setup Database
        run: |
          bundle install --jobs 4 --retry 3
          yarn install
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec